import type { Metadata } from "next";
import { Toaster } from "sonner";
import Providers from "../components/providers";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className="isolate">
          {children}
          <Toaster />
          <Analytics />
        </body>
      </html>
    </Providers>
  );
}
